Attribute VB_Name = "ReportGenerator"
Option Explicit

Public Function GenerateValidationReport(oResult As ValidationResult, oFileInfo As FileInfo, sSourceFile As String) As String
    Const sPROC_NAME As String = "GenerateValidationReport"
    
    On Error GoTo ErrorHandler
    
    Dim sReportPath As String
    Dim sReportContent As String
    
    ' Create report filename
    sReportPath = Environ("USERPROFILE") & "\Downloads\ValidationReport_" & _
                  format(Now, "yyyymmdd_hhnnss") & ".txt"
    
    ' Build report content
    sReportContent = BuildReportContent(oResult, oFileInfo, sSourceFile)
    
    ' Write report to file
    Dim lFileNum As Long
    lFileNum = FreeFile
    Open sReportPath For Output As #lFileNum
    Print #lFileNum, sReportContent
    Close #lFileNum
    
    GenerateValidationReport = sReportPath
    Exit Function
    
ErrorHandler:
    If lFileNum > 0 Then Close #lFileNum
    Call ErrorHandler_Central(sPROC_NAME, err.Number, err.description)
    GenerateValidationReport = ""
End Function

Private Function BuildReportContent(oResult As ValidationResult, oFileInfo As FileInfo, sSourceFile As String) As String
    Dim sContent As String
    
    sContent = "FILE VALIDATION REPORT" & vbCrLf
    sContent = sContent & String(50, "=") & vbCrLf & vbCrLf
    
    ' File Information
    sContent = sContent & "FILE INFORMATION:" & vbCrLf
    sContent = sContent & "Source File: " & sSourceFile & vbCrLf
    sContent = sContent & "File Name: " & oFileInfo.FileName & vbCrLf
    sContent = sContent & "File Type: " & oFileInfo.FileType & vbCrLf
    sContent = sContent & "Group ID: " & oFileInfo.GroupID & vbCrLf
    sContent = sContent & "File Date: " & format(oFileInfo.FileDate, "MM/DD/YYYY") & vbCrLf
    sContent = sContent & "Validation Date: " & format(Now, "MM/DD/YYYY HH:NN:SS") & vbCrLf & vbCrLf
    
    ' Summary
    sContent = sContent & "VALIDATION SUMMARY:" & vbCrLf
    sContent = sContent & "Total Records: " & oResult.TotalRecords & vbCrLf
    sContent = sContent & "Error Count: " & oResult.ErrorCount & vbCrLf
    sContent = sContent & "Warning Count: " & oResult.WarningCount & vbCrLf
    sContent = sContent & "Validation Status: " & IIf(oResult.IsValid, "PASSED", "FAILED") & vbCrLf & vbCrLf
    
    ' Detailed Errors
    If oResult.ErrorCount > 0 Then
        sContent = sContent & "DETAILED ERRORS:" & vbCrLf
        sContent = sContent & String(20, "-") & vbCrLf
        
        Dim i As Long
        For i = 1 To oResult.Errors.Count
            Dim oError As ValidationError
            Set oError = oResult.Errors.Item(i)
            
            sContent = sContent & "Row " & oError.RowNumber & ", Field '" & oError.FieldName & "': " & oError.ErrorMessage & vbCrLf
        Next i
    End If
    
    ' Warnings
    If oResult.WarningCount > 0 Then
        sContent = sContent & vbCrLf & "WARNINGS:" & vbCrLf
        sContent = sContent & String(10, "-") & vbCrLf
        
        For i = 1 To oResult.Warnings.Count
            Dim oWarning As ValidationError
            Set oWarning = oResult.Warnings.Item(i)
            
            sContent = sContent & "Row " & oWarning.RowNumber & ", Field '" & oWarning.FieldName & "': " & oWarning.ErrorMessage & vbCrLf
        Next i
    End If
    
    sContent = sContent & vbCrLf & String(50, "=") & vbCrLf
    sContent = sContent & "Report generated by File Validation System v1.0"
    
    BuildReportContent = sContent
End Function

