name: Build Check

on:
  push:
    branches:
      - main # or your protected branch name like master
  pull_request:
    branches:
      - main # or your protected branch name like master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Simple Test
        run: echo "This is a basic check. Replace with your actual build/test commands."
